/**
 * ConversationMessage – our wrapper around Anthropic's MessageParam that adds
 * a stable, SDK‑agnostic identifier and lightweight metadata we need for
 * bookkeeping (checkpoints, UI look‑ups, etc.).
 *
 * NOTE:  We deliberately keep the wrapper minimal.  Extra fields can be added
 * later without changing the external contract because consumer code continues
 * to access the raw Anthropic object via the `anthropic` property or via
 * `ContextWindow.getMessages()` which exposes only the Anthropic shape.
 */

import { Anthropic } from '@anthropic-ai/sdk';

export interface ConversationMessage {
  /**
   * Stable unique identifier for this message, generated by the client – not
   * by Anthropic.
   */
  id: string;

  /**
   * The underlying Anthropic message that is sent to / received from the API.
   */
  anthropic: Anthropic.Messages.MessageParam;

  /**
   * Epoch‑ms timestamp indicating when we inserted the message into the
   * context window.  Used for simple latency / ordering diagnostics.  (Not
   * required by the user right now, but adding it is effectively free.)
   */
  createdAt: number;
}
